name = "tus-server"
main = "src/index.ts"
compatibility_date = "2023-05-10"
compatibility_flags = ["nodejs_compat"]
logpush = true

# --- 默认配置 (直接指向你的正式桶) ---
r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "antenna-v2-attachments", preview_bucket_name = "antenna-v2-attachments" },
    { binding = "BACKUP_BUCKET", bucket_name = "antenna-v2-backups", preview_bucket_name = "antenna-v2-backups" }
]

durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]

[[migrations]]
tag = "v1"
new_classes = ["UploadHandler"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "UploadHandler", to = "AttachmentUploadHandler" }]
new_classes = ["BackupUploadHandler"]

# --- 生产环境显式定义 ---
[env.production]
name = "cdn3"
r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "antenna-v2-attachments", preview_bucket_name = "antenna-v2-attachments" },
    { binding = "BACKUP_BUCKET", bucket_name = "antenna-v2-backups", preview_bucket_name = "antenna-v2-backups" }
]
durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]
